habitat:
    gym:
        auto_name: NavToObj
        obs_keys:
        - robot_head_depth
        - object_to_agent_gps_compass
        - joint
        - nav_to_skill
    environment:
        max_episode_steps: 400
    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
        scenes_dir: data/replica_cad/
    task:
        type: NavToObjTask-v0
        must_look_at_targ: true
        force_regenerate: false
        object_in_hand_sample_prob: 0.167
        constraint_violation_ends_episode: false
        constraint_violation_drops_object: true
        count_obj_collisions: true
        filter_nav_to_tasks: []
        task_spec_base_path: tasks/rearrange/pddl/
        task_spec: nav_pick_nav_place
        pddl_domain_def: replica_cad
        obj_succ_thresh: 0.3
        art_succ_thresh: 0.15
        reward_measure: nav_to_obj_reward
        success_measure: nav_to_obj_success
        success_reward: 10.0
        slack_reward: 0.0
        end_on_success: true
        target_start_point_goal_sensor:
            type: TargetOrGoalStartPointGoalSensor
        nav_to_skill_sensor:
            type: NavToSkillSensor
            num_skills: 8
        joint_sensor:
            type: JointSensor
            dimensionality: 7
        sensors:
        - target_start_point_goal_sensor
        - joint_sensor
        - nav_to_skill_sensor
        robot_force:
            type: RobotForce
            min_force: 20.0
        force_terminate:
            type: ForceTerminate
            max_accum_force: -1.0
            max_instant_force: 10000.0
        robot_colls:
            type: RobotCollisions
        object_to_goal_distance:
            type: ObjectToGoalDistance
        rot_dist_to_goal:
            type: RotDistToGoal
        dist_to_goal:
            type: DistToGoal
        bad_called_terminate:
            type: BadCalledTerminate
            bad_term_pen: 0.0
            decay_bad_term: false
        num_steps:
            type: NumStepsMeasure
        rearrange_nav_to_obj_reward:
            type: NavToObjReward
            should_reward_turn: true
            turn_reward_dist: 0.6
            angle_dist_reward: 1.0
            dist_reward: 10.0
            constraint_violate_pen: 10.0
            force_pen: 0.0
            max_force_pen: 1.0
            force_end_pen: 5.0
        nav_to_pos_succ:
            type: NavToPosSucc
            success_distance: 0.3
        rearrange_nav_to_obj_success:
            type: NavToObjSuccess
            must_look_at_targ: true
            success_angle_dist: 0.3
            heuristic_stop: false
        measurements:
        - object_to_goal_distance
        - robot_force
        - force_terminate
        - robot_colls
        - rot_dist_to_goal
        - dist_to_goal
        - nav_to_pos_succ
        - rearrange_nav_to_obj_success
        - bad_called_terminate
        - rearrange_nav_to_obj_reward
        - num_steps
        actions:
            base_velocity:
                type: BaseVelAction
                lin_speed: 10.0
                ang_speed: 10.0
                allow_dyn_slide: true
                allow_back: true
                end_on_stop: true
                min_abs_lin_speed: 1.0
                min_abs_ang_speed: 1.0
        possible_actions:
        - base_velocity
    simulator:
        additional_object_paths:
        - data/objects/ycb/configs/
        action_space_config: v0
        debug_render: false
        debug_render_goal: false
        agents:
        - agent_0
        agent_0:
            height: 1.5
            radius: 0.3
            sensors:
            - head_depth_sensor
            robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
            robot_type: FetchSuctionRobot
            ik_arm_urdf: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
        head_depth_sensor:
            width: 256
            height: 256
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: true
        ctrl_freq: 120.0
        ac_freq_ratio: 4
        forward_step_size: 0.25
        hold_thresh: 0.2
        grasp_impulse: 10000.0
        default_agent_id: 0
        habitat_sim_v0:
            allow_sliding: false
            enable_physics: true
            gpu_device_id: 0
            gpu_gpu: false
            physics_config_file: ./data/default.physics_config.json
        seed: 100
        type: RearrangeSim-v0
        needs_markers: false
        arm_depth_sensor:
            width: 128
            height: 128
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: true
        head_rgb_sensor:
            width: 256
            height: 256
        arm_rgb_sensor:
            height: 128
            width: 128
