# The configuration to run the SensePlanAct baseline architecture from https://arxiv.org/abs/2106.14405
habitat:
    environment:
        max_episode_steps: 30
    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
        scenes_dir: "data/replica_cad/"
    task:
        type: RearrangePickTask-v0
        count_obj_collisions: True
        desired_resting_position: [0.5, 0.0, 1.0]
        constraint_violation_ends_episode: True

        should_enforce_target_within_reach: False

        # In radians
        base_angle_noise: 0.15
        base_noise: 0.05
        force_regenerate: False

        # If true, does not care about navigability or collisions with objects when spawning
        # robot
        easy_init: False

        target_start_sensor:
            type: "TargetStartSensor"
            goal_format: "CARTESIAN"
            dimensionality: 3
        goal_sensor:
            type: "GoalSensor"
            goal_format: "CARTESIAN"
            dimensionality: 3
        object_sensor:
            type: "TargetCurrentSensor"
            goal_format: "CARTESIAN"
            dimensionality: 3
        abs_target_start_sensor:
            type: "AbsTargetStartSensor"
            goal_format: "CARTESIAN"
            dimensionality: 3
        ABS_goal_sensor:
            type: "AbsGoalSensor"
            goal_format: "CARTESIAN"
            dimensionality: 3
        joint_sensor:
            type: "JointSensor"
            dimensionality: 7
        end_effector_sensor:
            type: "EEPositionSensor"
        is_holding_sensor:
            type: "IsHoldingSensor"
        relative_resting_pos_sensor:
            type: "RelativeRestingPositionSensor"
        sensors: ["target_start_sensor", "goal_sensor", "joint_sensor", "is_holding_sensor", "end_effector_sensor", "object_sensor", "relative_resting_pos_sensor"]
        robot_force:
            type: "RobotForce"
            min_force: 20.0
        robot_colls:
            type: "RobotCollisions"
        object_to_goal_distance:
            type: "ObjectToGoalDistance"
        end_effector_to_object_distance:
            type: "EndEffectorToObjectDistance"
        end_effector_to_rest_distance:
            type: "EndEffectorToRestDistance"
        force_terminate:
            type: "ForceTerminate"
            max_accum_force: 0.0
        pick_reward:
            type: "RearrangePickReward"
            dist_reward: 10.0
            pick_reward: 5.0
            constraint_violate_pen: 10.0
            drop_pen: 5.0
            wrong_pick_pen: 5.0

            force_pen: 0.0
            max_force_pen: 0.0
            force_end_pen: 0.0
            use_diff: True

            drop_obj_should_end: False
            wrong_pick_should_end: False
        pick_success:
            type: "RearrangePickSuccess"
            ee_resting_success_threshold: 0.15
        num_steps:
            type: "NumStepsMeasure"
        measurements:
            - "robot_force"
            - "robot_colls"
            - "force_terminate"
            - "end_effector_to_rest_distance"
            - "end_effector_to_object_distance"
            - "pick_success"
            - "pick_reward"
            - "num_steps"
        actions:
            arm_action:
                type: "ArmAction"
                arm_controller: "ArmAbsPosKinematicAction"
                grip_controller: "MagicGraspAction"
                arm_joint_dimensionality: 7
                grasp_thresh_dist: 0.15
                disable_grip: False
                delta_pos_limit: 0.0125
                ee_ctrl_lim: 0.015
            empty:
                type: "EmptyAction"
        possible_actions:
            - arm_action
            - empty

    simulator:
        additional_object_paths:
            - "data/objects/ycb/configs/"
        action_space_config: v0
        debug_render: False
        debug_render_goal: True
        agents: ['agent_0']
        concur_render: True
        auto_sleep: True
        agent_0:
            height: 1.5
            radius: 0.3
            sensors: ['head_rgb_sensor', 'head_depth_sensor', 'arm_rgb_sensor', 'arm_depth_sensor', 'third_rgb_sensor']
            robot_urdf: ./data/robots/hab_fetch/robots/hab_fetch.urdf
            robot_type: "FetchRobot"
            ik_arm_urdf: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
        head_rgb_sensor:
            width: 128
            height: 128
        head_depth_sensor:
            width: 128
            height: 128
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: True
        arm_depth_sensor:
            height: 128
            max_depth: 10.0
            min_depth: 0.0
            normalize_depth: True
            width: 128
        arm_rgb_sensor:
            height: 128
            width: 128
        third_rgb_sensor:
            width: 512
            height: 512

        # Agent setup
        ctrl_freq: 120.0
        ac_freq_ratio: 8
        forward_step_size: 0.25

        # Grasping
        hold_thresh: 0.09
        grasp_impulse: 1000.0

        default_agent_id: 0
        habitat_sim_v0:
            allow_sliding: False
            enable_physics: True
            gpu_device_id: 0
            gpu_gpu: False
            physics_config_file: ./data/default.physics_config.json
        seed: 100
        semantic_sensor:
            height: 480
            hfov: 90
            orientation: [0.0, 0.0, 0.0]
            position: [0, 1.25, 0]
            type: HabitatSimSemanticSensor
            width: 640
        tilt_angle: 15
        turn_angle: 10
        type: RearrangeSim-v0
