habitat:
    gym:
        auto_name: PrepareGroceries
        obs_keys:
        - robot_head_depth
        - relative_resting_position
        - obj_start_sensor
        - obj_goal_sensor
        - obj_start_gps_compass
        - obj_goal_gps_compass
        - joint
        - is_holding
    environment:
        max_episode_steps: 4000
    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/datasets/replica_cad/rearrange/v1/{split}/prepare_groceries_10k_1k.json.gz
        scenes_dir: data/replica_cad/
    task:
        type: RearrangeCompositeTask-v0
        reward_measure: move_obj_reward
        success_measure: composite_success
        success_reward: 100.0
        slack_reward: -0.01
        end_on_success: true
        count_obj_collisions: true
        constraint_violation_ends_episode: false
        base_angle_noise: 0.15
        base_noise: 0.05
        easy_init: false
        task_spec_base_path: tasks/rearrange/pddl/
        task_spec: prepare_groceries
        pddl_domain_def: replica_cad
        sensors:
        - relative_resting_pos_sensor
        - target_start_sensor
        - goal_sensor
        - joint_sensor
        - is_holding_sensor
        - end_effector_sensor
        - target_start_gps_compass_sensor
        - target_goal_gps_compass_sensor
        force_terminate:
            type: ForceTerminate
            max_accum_force: -1.0
        robot_force:
            type: RobotForce
            min_force: 20.0
        measurements:
        - object_to_goal_distance
        - robot_force
        - force_terminate
        - robot_colls
        - end_effector_to_object_distance
        - does_want_terminate
        - composite_success
        - composite_bad_called_terminate
        - num_steps
        - did_violate_hold_constraint
        - move_objects_reward
        - composite_stage_goals
        actions:
            arm_action:
                type: ArmAction
                arm_controller: ArmRelPosAction
                grip_controller: MagicGraspAction
                arm_joint_dimensionality: 7
                grasp_thresh_dist: 0.15
                disable_grip: false
                delta_pos_limit: 0.0125
                ee_ctrl_lim: 0.015
            base_velocity:
                type: BaseVelAction
                lin_speed: 10.0
                ang_speed: 10.0
                allow_dyn_slide: true
                end_on_stop: false
                allow_back: true
                min_abs_lin_speed: 1.0
                min_abs_ang_speed: 1.0
            rearrange_stop:
                type: RearrangeStopAction
        possible_actions:
        - arm_action
        - base_velocity
        - rearrange_stop
        move_objects_reward:
            type: MoveObjectsReward
            pick_reward: 1.0
            success_dist: 0.15
            single_rearrange_reward: 1.0
            dist_reward: 1.0
            constraint_violate_pen: 10.0
            force_pen: 0.0
            max_force_pen: 1.0
            force_end_pen: 10.0
    simulator:
        additional_object_paths:
            - "data/objects/ycb/configs/"
        action_space_config: v0
        grasp_impulse: 1000.0
        hold_thresh: 0.09
        ac_freq_ratio: 4
        debug_render: false
        debug_render_goal: true
        agents:
        - agent_0
        concur_render: true
        auto_sleep: true
        agent_0:
            height: 1.5
            radius: 0.3
            sensors:
            - head_depth_sensor
            robot_urdf: ./data/robots/hab_fetch/robots/hab_fetch.urdf
            robot_type: FetchRobot
            ik_arm_urdf: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
        head_rgb_sensor:
            width: 128
            height: 128
        head_depth_sensor:
            width: 128
            height: 128
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: true
        arm_depth_sensor:
            height: 128
            max_depth: 10.0
            min_depth: 0.0
            normalize_depth: true
            width: 128
        arm_rgb_sensor:
            height: 128
            width: 128
        ctrl_freq: 120.0
        default_agent_id: 0
        forward_step_size: 0.25
        habitat_sim_v0:
            allow_sliding: false
            enable_physics: true
            gpu_device_id: 0
            gpu_gpu: false
            physics_config_file: ./data/default.physics_config.json
        seed: 100
        type: RearrangeSim-v0
