habitat:
    gym:
        auto_name: "ReachState"
        obs_keys: ['joint', 'relative_resting_position']
        action_keys: ['arm_action']
    environment:
        max_episode_steps: 20
    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/datasets/replica_cad/rearrange/v1/{split}/empty_1k_100.json.gz
        scenes_dir: "data/replica_cad/"
    task:
        base_angle_noise: 0.0
        base_noise: 0.0
        type: RearrangeReachTask-v0
        render_target: True
        ee_sample_factor: 0.2
        ee_exclude_region: 0.0

        reward_measure: "rearrange_reach_reward"
        success_measure: "rearrange_reach_success"
        success_reward: 10.0
        end_on_success: True

        joint_sensor:
            type: "JointSensor"
            dimensionality: 7
        relative_resting_pos_sensor:
            type: "RelativeRestingPositionSensor"
        resting_pos_sensor:
            type: "RestingPositionSensor"
        end_effector_sensor:
            type: "EEPositionSensor"
        joint_velocity_sensor:
            type: "JointVelocitySensor"
            dimensionality: 7
        sensors: ["joint_sensor", "joint_velocity_sensor", "relative_resting_pos_sensor"]

        end_effector_to_rest_distance:
            type: "EndEffectorToRestDistance"
        rearrange_reach_reward:
            type: "RearrangeReachReward"
            scale: 1.0
            diff_reward: True
            sparse_reward: False
        rearrange_reach_success:
            type: "RearrangeReachSuccess"
            succ_thresh: 0.2
        num_steps:
            type: "NumStepsMeasure"
        measurements:
            - "end_effector_to_rest_distance"
            - "rearrange_reach_success"
            - "rearrange_reach_reward"
            - "num_steps"
        actions:
            arm_action:
                type: "ArmAction"
                arm_controller: "ArmRelPosAction"
                arm_joint_dimensionality: 7
                grip_controller: null
                grasp_thresh_dist: 0.15
                should_clip: True
                delta_pos_limit: 0.0125
                render_ee_target: True
                ee_ctrl_lim: 0.015
        possible_actions:
            - arm_action

    simulator:
        action_space_config: v0
        agents: ['agent_0']
        concur_render: True
        auto_sleep: True
        debug_render: False
        debug_render_goal: True
        agent_0:
            height: 1.5
            is_set_start_state: True
            radius: 0.3
            sensors: [head_depth_sensor]
            start_position: [0.0, 0.0, 2.0]
            start_rotation: [0.0, 0.0, 0.0, 1.0]
            robot_urdf: ./data/robots/hab_fetch/robots/hab_fetch.urdf
            ik_arm_urdf: null
            robot_type: "FetchRobot"
        head_depth_sensor:
            width: 32
            height: 32
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: True

        # Agent setup
        ctrl_freq: 120.0
        ac_freq_ratio: 8
        forward_step_size: 0.25

        # Grasping
        hold_thresh: 0.09
        grasp_impulse: 1000.0

        default_agent_id: 0
        habitat_sim_v0:
            allow_sliding: False
            enable_physics: True
            gpu_device_id: 0
            gpu_gpu: False
            physics_config_file: ./data/default.physics_config.json
        seed: 100
        semantic_sensor:
            height: 480
            hfov: 90
            orientation: [0.0, 0.0, 0.0]
            position: [0, 1.25, 0]
            type: HabitatSimSemanticSensor
            width: 640
        tilt_angle: 15
        turn_angle: 10
        type: RearrangeSim-v0
