habitat:
    gym:
        auto_name: RearrangeEasyMultiAgent
        obs_keys:
        - agent_0_robot_head_depth
        - agent_1_robot_head_depth
        - agent_0_obj_start_sensor
        - agent_1_obj_start_sensor
        - agent_0_obj_goal_sensor
        - agent_1_obj_goal_sensor
        - agent_0_joint
        - agent_1_joint
    environment:
        max_episode_steps: 1500
    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
        scenes_dir: data/replica_cad/
    task:
        type: RearrangeCompositeTask-v0
        reward_measure: composite_success
        success_measure: composite_success
        success_reward: 100.0
        slack_reward: -0.01
        end_on_success: true
        count_obj_collisions: true
        constraint_violation_ends_episode: false
        constraint_violation_drops_object: True
        base_angle_noise: 0.15
        base_noise: 0.05
        easy_init: false
        task_spec_base_path: tasks/rearrange/pddl/
        task_spec: rearrange_easy
        pddl_domain_def: replica_cad
        obj_succ_thresh: 0.3
        art_succ_thresh: 0.15

        # The sensor spec is specified per agent and then duplicated
        # across each agent (a homogenous observation space). If the sensor derives
        # from `UsesRobotInterface` then it is automatically duplicated.
        # Hetrogeneous observation spaces are also supported by not deriving from
        # `UsesRobotInterface`.
        sensors:
        - relative_resting_pos_sensor
        - target_start_sensor
        - goal_sensor
        - joint_sensor
        - is_holding_sensor
        - end_effector_sensor
        - target_start_gps_compass_sensor
        - target_goal_gps_compass_sensor
        force_terminate:
            type: ForceTerminate
            max_accum_force: 100_000.0
            max_instant_force: 10_000.0
        composite_success:
            must_call_stop: False
        # Unlike sensors, measurements are not automatically duplicated per agent.
        measurements:
        - object_to_goal_distance
        - robot_force
        - force_terminate
        - robot_colls
        - composite_success
        - num_steps
        actions:
            # Actions are defined per agent. Unlike the sensors, actions are not
            # automatically duplicated per agent.
            agent_0_arm_action:
                agent: 0
                type: ArmAction
                arm_controller: ArmRelPosAction
                grip_controller: MagicGraspAction
                arm_joint_dimensionality: 7
                grasp_thresh_dist: 0.15
                disable_grip: false
                delta_pos_limit: 0.0125
                ee_ctrl_lim: 0.015
            agent_0_base_velocity:
                agent: 0
                type: BaseVelAction
                lin_speed: 10.0
                ang_speed: 10.0
                allow_dyn_slide: true
                end_on_stop: false
                allow_back: true
                min_abs_lin_speed: 1.0
                min_abs_ang_speed: 1.0
            agent_1_arm_action:
                agent: 1
                type: ArmAction
                arm_controller: ArmRelPosAction
                grip_controller: MagicGraspAction
                arm_joint_dimensionality: 7
                grasp_thresh_dist: 0.15
                disable_grip: false
                delta_pos_limit: 0.0125
                ee_ctrl_lim: 0.015
            agent_1_base_velocity:
                agent: 1
                type: BaseVelAction
                lin_speed: 10.0
                ang_speed: 10.0
                allow_dyn_slide: true
                end_on_stop: false
                allow_back: true
                min_abs_lin_speed: 1.0
                min_abs_ang_speed: 1.0
            agent_0_rearrange_stop:
                type: RearrangeStopAction
            agent_1_rearrange_stop:
                type: RearrangeStopAction
            possible_actions:
            - agent_0_arm_action
            - agent_0_base_velocity
            - agent_0_rearrange_stop
            - agent_1_arm_action
            - agent_1_base_velocity
            - agent_1_rearrange_stop
    simulator:
        additional_object_paths:
            - "data/objects/ycb/configs/"
        action_space_config: v0
        grasp_impulse: 10000.0
        hold_thresh: 0.2
        ac_freq_ratio: 4
        debug_render: false
        debug_render_goal: true
        agents:
        - agent_0
        - agent_1
        agent_0:
            height: 1.5
            radius: 0.3
            is_set_start_state: false
            sensors:
            - head_depth_sensor
            robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
            robot_type: FetchSuctionRobot
            ik_arm_urdf: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
            joint_start_noise: 0.0
        agent_1:
            height: 1.5
            radius: 0.3
            is_set_start_state: false
            # A new instance of the sensor is created. The agents do not share a
            # depth camera, but instead a different depth camera is created for
            # each agent.
            sensors:
            - head_depth_sensor
            robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
            robot_type: FetchSuctionRobot
            ik_arm_urdf: ./data/robots/hab_fetch/robots/fetch_onlyarm.urdf
            joint_start_noise: 0.0
        head_rgb_sensor:
            width: 256
            height: 256
        head_depth_sensor:
            width: 256
            height: 256
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: true
        ctrl_freq: 120.0
        default_agent_id: 0
        forward_step_size: 0.25
        habitat_sim_v0:
            allow_sliding: false
            enable_physics: true
            gpu_device_id: 0
            gpu_gpu: false
            physics_config_file: ./data/default.physics_config.json
        seed: 100
        type: RearrangeSim-v0
