habitat:
    environment:
        # Endless episode
        max_episode_steps: 0

    dataset:
        type: RearrangeDataset-v0
        split: train
        data_path: data/ep_datasets/bench_scene.json.gz
        scenes_dir: "data/replica_cad/"

    task:
        # No task logic, empty task
        type: RearrangeEmptyTask-v0

        # If true, does not care about navigability or collisions with objects when spawning
        # robot
        easy_init: False
        desired_resting_position: [0.5, 0.0, 1.0]
        constraint_violation_ends_episode: False

        actions:
            arm_action:
                type: "ArmAction"
                arm_controller: "ArmRelPosAction"
                grip_controller: "MagicGraspAction"
                arm_joint_dimensionality: 7
                grasp_thresh_dist: 0.15
                disable_grip: False
                ee_ctrl_lim: 0.015
                delta_pos_limit: 0.025
        possible_actions:
            - arm_action

    simulator:
        ############################
        # Benchmark relevant settings
        ############################
        concur_render: True
        auto_sleep: True
        step_physics: True
        update_robot: True
        ############################

        additional_object_paths:
            - "data/objects/ycb/configs/"

        seed: 100
        tilt_angle: 15
        turn_angle: 10
        type: RearrangeSim-v0

        habitat_sim_v0:
            allow_sliding: True
            enable_physics: True
            physics_config_file: ./data/default.physics_config.json
            gpu_device_id: 0

        agents: ['agent_0']
        agent_0:
            sensors: ['head_rgb_sensor', 'head_depth_sensor', 'arm_rgb_sensor', 'arm_depth_sensor']
            height: 1.5
            radius: 0.1
            is_set_start_state: True
            start_position: [-1.2, 0.158, 0.29]
            start_rotation: [0.0, 0.999657, 0.0, -0.0261769]
            robot_type: FetchRobotNoWheels
            robot_urdf: ./data/robots/hab_fetch/robots/fetch_no_base.urdf
        head_rgb_sensor:
            width: 128
            height: 128
        head_depth_sensor:
            width: 128
            height: 128
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: True
        arm_depth_sensor:
            height: 128
            max_depth: 10.0
            min_depth: 0.0
            normalize_depth: True
            width: 128
        arm_rgb_sensor:
            height: 128
            width: 128

        # Agent setup
        ctrl_freq: 120.0
        ac_freq_ratio: 4
        forward_step_size: 0.25

        # Grasping
        hold_thresh: 0.09
        grasp_impulse: 1000.0
