# Note:  This is an example config, see habitat-baselines/habitat_baselines/config/pointnav/ppo_pointnav.yaml
# for better hyperparameters for actual training

habitat_baselines:
  verbose: False

#  base_task_config_path: "habitat-lab/habitat/config/tasks/pointnav.yaml"
#  base_task_config_path: "habitat-baselines/habitat_baselines/config/tasks/pointnav.yaml"
  base_task_config_path: "habitat-baselines/habitat_baselines/config/tasks/pointnav_mp3d.yaml"
  trainer_name: "ppo"
  simulator_gpu_id: 0
  torch_gpu_id: 0
  video_option: ["disk", "tensorboard"]
  video_save: False
  tensorboard_dir: "tb/mp3d/depth"
  video_dir: "result/mp3d/depth"
  # To evaluate on all episodes, set this to -1
  test_episode_count: 494
  num_environments: 1
#  eval_ckpt_path_dir: "data/new_checkpoints"
#  eval_ckpt_path_dir: "/data/chengyang/habitat-result/model"
  eval_ckpt_path_dir: "/data/chengyang/habitat-result/model/mp3d-depth-best.pth"
  sensors: ["depth_sensor"]
  # sensors: ["rgb_sensor", "depth_sensor"]
#  checkpoint_folder: "data/new_checkpoints"
  checkpoint_folder: "/data/chengyang/habitat-result/result"
  num_updates: -1
  total_num_steps: 1e6
  log_interval: 10
  num_checkpoints: 50
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True

  eval:
    evaluate_strategy: 0
    eta: 0.03
    update_num: 1
    traj_num_each: 5

  rl:
    ppo:
      # ppo params
      clip_param: 0.1
      ppo_epoch: 1
      num_mini_batch: 1
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.5
      num_steps: 32
      hidden_size: 512
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: True
      use_linear_lr_decay: True
      reward_window_size: 50
