habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agent_0:
      sensors: ['rgb_sensor']
    habitat_sim_v0:
      gpu_device_id: 0
    rgb_sensor:
      width: 256
      height: 256
    depth_sensor:
      width: 256
      height: 256
  task:
    type: Nav-v0

    end_on_success: True
    reward_measure: "distance_to_goal_reward"
    success_measure: "spl"


    sensors: ['pointgoal_with_gps_compass_sensor']
    pointgoal_with_gps_compass_sensor:
      goal_format: "POLAR"
      dimensionality: 2
    goal_sensor_uuid: pointgoal_with_gps_compass

    measurements: ['distance_to_goal', 'success', 'spl', 'distance_to_goal_reward']
    success:
      success_distance: 0.2

  dataset:
    type: PointNav-v1
    split: val
#    data_path: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
    data_path: scene_data/datasets/pointnav_gibson/{split}/{split}.json.gz
    scenes_dir: scene_data/scene_datasets/gibson_habitat
