habitat:
  task:
    type: EQA-v0
    sensors: ['question_sensor']
    possible_actions: ['move_forward', 'turn_left', 'turn_right', 'answer']
    measurements: ['episode_info', 'distance_to_goal', 'answer_accuracy']

  environment:
    max_episode_steps: 500

  simulator:
    agent_0:
      sensors: ['rgb_sensor', 'semantic_sensor', 'depth_sensor']
    habitat_sim_v0:
      gpu_device_id: 0
    rgb_sensor:
      width: 256
      height: 256
    depth_sensor:
      width: 256
      height: 256
    semantic_sensor:
      width: 256
      height: 256

  dataset:
    type: MP3DEQA-v1
    split: train
    data_path: "data/datasets/eqa/mp3d/v1/{split}/{split}.json.gz"
    scenes_dir: "data/scene_datasets/"
