habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agent_0:
      sensors: ['rgb_sensor']
      robot_urdf: ./data/robots/franka_panda/panda_arm.urdf
      robot_type: "FrankaRobot"
    habitat_sim_v0:
      gpu_device_id: 0
    rgb_sensor:
      width: 256
      height: 256
    depth_sensor:
      width: 256
      height: 256
  task:
    type: Nav-v0

    sensors: ['pointgoal_with_gps_compass_sensor']
    pointgoal_with_gps_compass_sensor:
      goal_format: "POLAR"
      dimensionality: 2
    goal_sensor_uuid: pointgoal_with_gps_compass

    measurements: ['distance_to_goal', 'success', 'spl']
    success:
      success_distance: 0.2
