habitat:
  environment:
    max_episode_steps: 1000

  simulator:
    agent_0:
      sensors: ["rgb_sensor", "depth_sensor"]
    habitat_sim_v0:
      gpu_device_id: 0
    rgb_sensor:
      width: 256
      height: 256
    depth_sensor:
      width: 256
      height: 256

  task:
    type: Nav-v0

    end_on_success: True
    reward_measure: "distance_to_goal_reward"
    success_measure: "spl"

    sensors: ['imagegoal_sensor']

    measurements: ["distance_to_goal", "success", "spl", "soft_spl", 'distance_to_goal_reward']
    success:
      success_distance: 1.
