habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agent_0:
      sensors: ['rgb_sensor', 'depth_sensor']
    forward_step_size: 0.25
    turn_angle: 15
    habitat_sim_v0:
      gpu_device_id: 0
    rgb_sensor:
      width: 256
      height: 256
      hfov: 90
      type: HabitatSimRGBSensor
    depth_sensor:
      width: 256
      height: 256
  task:
    type: VLN-v0
    sensors: ['instruction_sensor']
    possible_actions: ['stop', 'move_forward', 'turn_left', 'turn_right']
    measurements: ['distance_to_goal', 'success', 'spl']
  dataset:
    type: R2RVLN-v1
    split: train
    data_path: "data/datasets/vln/mp3d/r2r/v1/{split}/{split}.json.gz"
    scenes_dir: "data/scene_datasets/"
